name: EnchantmentSolutionLegacy
version: 0.9.1
main: org.ctp.enchantmentsolution.EnchantmentSolution
commands:
  enchant:
    aliases: [es,customenchant]
    description: Add enchantments to items.
    usage: /enchant <enchant_name> [level]
  enchantunsafe:
    aliases: [esu,customenchantunsafe]
    description: Displays commands
    usage: /enchantunsafe <enchant_name> [level]
  info:
    aliases: [einfo,enchantinfo]
    description: Gives player information on an enchantment.
    usage: /info [enchant_name]
  removeenchant:
    aliases: [esr,eremove]
    description: Remove enchantment from item.
    usage: /removeenchant <enchant_name>
  esreload:
    description: Reload config files
    usage: /esreload
  esconfig:
    description: Edit config files
    usage: /esconfig
  esreset:
    description: Reset all custom inventories
    usage: /esreset
permissions:
  enchantmentsolution.command.edit: 
    description: Gives access to the /esconfig command. 
    default: op
  enchantmentsolution.command.enchant: 
    description: Gives access to the /enchant command. 
    default: op
  enchantmentsolution.command.reload: 
    description: Gives access to the /esreload command. 
    default: op
  enchantmentsolution.command.enchantremove: 
    description: Gives access to the /removeenchant command. 
    default: op
  enchantmentsolution.command.reset: 
    description: Gives access to the /esreset command. 
    default: op
  enchantmentsolution.command.enchantunsafe: 
    description: Gives access to the /enchantunsafe command.
    default: op
  enchantmentsolution.enable-flight:
    description: Enables use of external /fly commands without interference from FrequentFlyer
    default: false
  enchantmentsolution.permissions.ignore: 
    description: Gives access to all enchantment permissions.
    default: false